name: /data/mhoffert/miniconda3/envs/periodic_phyla
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - seaborn
  - matplotlib
  - pandas
  - numpy
  - jupyterlab
  - umap-learn
  - gensim
  - adjusttext
  - lxml
  - html5lib
  - hmmer
  - biopython
  - networkx
  - blast
  - flatten_json
  - xmltodict
  - pydot
  - openpyxl==3.0.10
  - ete3
  - fastcluster
  - esda
  - vsearch
  - seqmagick
  - mafft
  - cd-hit
  - imbalanced-learn
  - xlrd
  - pyqt=5.9.2
  - hdbscan
  - cython=0.29.30
  - fuzzywuzzy
  - matplotlib-venn
  - rapidfuzz
  - scikit-bio
  - scipy=1.8.0
  - ca-certificates
  - certifi
  - openssl
  - pip:
      - adjusttext==0.7.3
      - argon2-cffi==21.3.0
      - asttokens==2.0.5
      - attrs==21.4.0
      - babel==2.9.1
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.4
      - beautifulsoup4==4.11.1
      - bleach==5.0.0
      - charset-normalizer==2.0.12
      - colorama==0.4.4
      - contourpy==1.2.0
      - cycler==0.11.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - esda==2.4.1
      - executing==0.8.3
      - fastjsonschema==2.15.3
      - flatten-json==0.1.13
      - flit-core==3.7.1
      - html5lib==1.1
      - idna==3.3
      - imbalanced-learn==0.7.0
      - importlib-resources==5.7.1
      - ipython-genutils==0.2.0
      - jinja2==3.1.1
      - joblib==1.1.0
      - json5==0.9.5
      - jsonschema==4.4.0
      - jupyter-client==7.3.0
      - jupyter-server==1.17.0
      - jupyterlab==3.3.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.13.0
      - libpysal==4.1.1
      - mantel==2.2.0
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.3
      - munkres==1.1.4
      - nbclassic==0.3.7
      - nbclient==0.6.2
      - nbconvert==6.5.0
      - nbformat==5.3.0
      - nest-asyncio==1.5.5
      - networkx==2.7.1
      - notebook==6.4.11
      - notebook-shim==0.1.0
      - numpy==1.24.4
      - numpy-hilbert-curve==1.0.1
      - packaging==21.3
      - pandas==2.1.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - patsy==0.5.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pip==22.0.4
      - prometheus-client==0.14.1
      - prompt-toolkit==3.0.29
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pydot==1.2.4
      - pygments==2.12.0
      - pygtrie==2.4.2
      - pynndescent==0.5.6
      - pyopenssl==22.0.0
      - pyparsing==3.0.8
      - python-dateutil==2.8.2
      - pytz==2022.1
      - requests==2.27.1
      - seaborn==0.13.0
      - send2trash==1.8.0
      - seqmagick==0.8.4
      - six==1.16.0
      - smart-open==6.0.0
      - soupsieve==2.3.1
      - stack-data==0.2.0
      - threadpoolctl==3.1.0
      - tinycss2==1.1.1
      - tqdm==4.64.0
      - traitlets==5.1.1
      - urllib3==1.26.9
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.3.2
      - wheel==0.37.1
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - zipp==3.8.0
